# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc75cf7d6ad4d35ab3eaba46e1859ba1cb022721f8b9dafa37d0b4bb44869a56a059125927a2ca4f430835d0d1055f6582cd4c331d815069dfa8148b8b05d42

test:
  secret_key_base: 179dc762a4b785afb6e93ab9480c8077bf9f4e46cd1cfed17b00fa7b77093778e605a4a41c709d4a8ce6870cf1a525dab2694234c5093231c61d69a4d620f2a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
